### ISSUE TITLE
Sobre esse repositório

### ISSUE THREAD

**Issue by sibeliusseraphini** [sibeliusseraphini/react-native-dojo#1]
Esse repositório surgiu com uma ideia maluca de criar um Dojo remoto para aprender e fazer varias amizades.

Vamos utilizar essa issue para ideias e possiveis apps que gostaríamos de desenvolver.

A ideia é que desenvolvermos tanto a parte do servidor (nodejs), da web (react) e do mobile (react native)

# Como funcionaria
- Primeiro definimos o app que iremos desenvolver

- Criamos as primeiras issues que temos que resolver para avançar o desenvolvimento do app, e lançar a fase alpha dele

- Depois das primeiras issues criadas, serão escolhidos/sorteados 3 devs (1 para o servidor, 1 para a web, 1 para o react native, talvez 6 para que trabalhem 2 em cada issue) para tentar resolver 3 issues no periodo de 2 dias, e enviando um PR para esse repositorio (não importa se não conseguirem terminar a issue inteira, isso indica que não dividimos em pedaços pequenos suficientes para serem desenvolvidos em 2 dias)

- 3 outros Dev são responsáveis de revisar as PRs enviadas

- E assim o ciclo continua

Podemos criar um slack ou gitter para que um possa ajudar ao outro

Obs.: isso não está fechado e definido, tudo pode mudar

Comentem aqui com o usuário do github e com sua ideia, para que eu saiba que vocês querem participar desse Dojo experimental

**Comment by sibeliusseraphini** [comment]
@sibeliusseraphini

# Ideia
Aplicativo para as Olimpíadas 2016 do Brasil
- Mostrar Atletas por pais e suas habilidades
- Mostrar Histórico de Medalhas
- Mostar horário dos eventos
- Entre outras coisas

Podemos nos basear nesse app para a [NBA](https://github.com/wwayne/react-native-nba-app)

**Comment by henriquesosa** [comment]
Não seria bacana fazer uma company? Ia ficar mais facil de até centralizar os projetos assim que os mesmos começarem a aperecer

**Comment by rturk** [comment]
@rturk

# Ideia
Aplicativo para doação de sangue
- Mostrar Hospitais e pontos de coleta locais
- Push notification quando estoque de sangue estiver baixo
- Share em redes sociais
- Find friends
- Server side statistics


Podemos nos basear nesse app para a [NBA](https://github.com/wwayne/react-native-nba-app)

**Comment by sibeliusseraphini** [comment]
@henriquesosa pode ser sim, qual seria o nome: react-native-dojo?

vamos migrar para lá então, você cria ?

**Comment by henriquesosa** [comment]
@sibeliusseraphini @rturk Criei ja e  coloquei vocês ja enviei o convite para voces!!!!

**Comment by sibeliusseraphini** [comment]
moving to https://github.com/react-native-dojo/react-native-dojo
